### ISSUE TITLE
Potential mistranslation?

### ISSUE THREAD

**Issue by eromangaka** [DazedMTL/RJ01043101#22]
In commit c4e8840 in the dialogue lines for starting the mentai minigame, "have mentai" was changed to "play mentai", which of course makes logical sense in english because "mentai" isnt a common loan word, but it also breaks the wordplay in those dialogue lines. 

Mentai, like in the first game, is used as a pun, because it means both the coin flip game and food (fish roe). So most of the characters actually are asking if the MC wants to "have fish roe (with me)", rather than asking if he wants to play a game. And then the odd characters ask to both "play and have" mentai, which I think lends to the intentionality of the original authors word choice for those lines.

I think its a funny pun that fits the rest of the game, seems wrong to remove it.

**Comment by dazedanon** [comment]
That makes sense to me and I agree.

Can you leave this comment in the PR itself so that Shionel is aware when he makes his changes. I'll be sure to check for that before I consider merging the PR as well.

Either way play Mentai can easily be Find/Replaced with have Mentai so shouldn't be a problem correcting it in the future.

**Comment by eromangaka** [comment]
Ah its already been merged before I noticed that, which is why i opened an issue rather than comment on it, I just didnt want to correct it without getting an opinion.

I would have tagged Shionel in this ticket but unfortuately his profile doesnt seem to be available for that.

**Comment by shionels** [comment]
Thank you very much for the feedback! 
I swapped "have mentai" to "play mentai" with localization in mind.
I understand that you want to keep all the context from the author. However, readable context is often prioritized than local pun and/or word play, especially if they're too obscure within their country border.
As far as I've done localization, sometimes slight missing contexts are acceptable and/or unavoidable to omit for the sake of the readers having easier time to understand the main context.
Of course, we translators should apply pun that match the target language whenever possible,

All that said, I have no issue to revert it back, but I want to hear dazed decision too.
On side note, I believe certain publisher with "KGR" will use "play" as well

Lastly, I don't know how to allow my profile to receive tickets. I barely have chance to use github, so i didn't setup anything (despite this is an old account). So my apologizes

**Comment by dazedanon** [comment]
Hmm, I'm not sure. I understand where both of you are coming from.

How about we just keep it consistent with the first game. Do either you two know whether `Have Mentai` or `Play Mentai` was used in Summer Memories?

**Comment by shionels** [comment]
Did a quick check, It's "Menko match(es)" in summer memories apparently
![Capture](https://github.com/DazedMTL/RJ01043101/assets/16026831/bd47d6ff-024d-46fc-8d88-9fdf034e27f0)

**Comment by dazedanon** [comment]
Menko huh, looks like they didn't really have to worry about it then.

Let's go ahead and leave it as is then. Most English speakers are not going to understand the pun anyway unless we started doing TL notes. Since this is ultimately an MTL translation, people are just going to assume it was badly translated if we go with have/having Mentai instead.

Does that work for everyone?

**Comment by dazedanon** [comment]
I actually usually favor purity over localization as well, but in this specific instance I personally prefer the latter. I'm not by any means an expert on the subject so I can only go with my gut.

Therefore let's stick with play. 

Thanks you two for sharing your thoughts on the subject. I'll go ahead and close this issue.
